### ISSUE TITLE
Display canonical JSON form to ease comparison

### ISSUE THREAD

**Issue by Natim** [Kinto/kinto-admin#58] opened 2016-05-09 08:18 UTC
![canonical-json](https://cloud.githubusercontent.com/assets/229453/15107307/5a5bf9f6-15cf-11e6-9ee8-9a80b027d69e.png)

Please tell me the differences between the two :)

**Comment by n1k0** [comment] 2016-05-09 12:11
last_modified differs.

**Comment by n1k0** [comment] 2016-05-09 12:12
Oh, the issue is about rendering a diff, okay ;)

**Comment by n1k0** [comment] 2016-05-09 12:16
Most interesting lib found for now is https://github.com/flitbit/diff

**Comment by n1k0** [comment] 2016-05-11 12:07
Fixed by #61

**Closed by n1k0** 2016-05-11 12:07 UTC
Labels: enhancement
