### ISSUE TITLE
[minor] Truncated content title when a large notification is rendered

### ISSUE THREAD

**Issue by n1k0** [Kinto/kinto-admin#29] opened 2016-03-29 15:15 UTC
![](http://i.imgur.com/6vlezKu.png)

**Comment by PankajLala** [comment] 2016-04-01 06:30
I couldn't find the "notification" section, but seem like same problem with task collection title.
Can be addressed by removing _white-space: nowrap_ and adding _word-wrap: break-word_ to table.record-list td in style.css

![image](https://cloud.githubusercontent.com/assets/2928347/14199342/2912d15e-f7d3-11e5-8434-0cfec79a3d4e.png)

**Comment by magopian** [comment] 2016-04-01 07:53
The issue is with the notification "panel" at the top of the page, that you can see for example if you click on the "show advanced action" button, and then on the "Reset Sync Status" button.

**Closed** 2019-05-29 17:09 UTC
Labels: tech-debt, ux
