### ISSUE TITLE
does not appear to work with kinto 7.0.0.dev0

### ISSUE THREAD

**Issue by vladp** [Kinto/kinto-admin#421] opened 2017-04-01 21:11 UTC
new user, so could be my fault, 
but I am getting
```

Couldn't list buckets.
requests.0 in body: Unrecognized keys in mapping: "{'retry': 1, 'batch': True, 'safe': False, 'bucket': 'vsp_firstbucket_v1'}"
HTTP 400 Invalid parameters: Invalid request parameter (requests.0 in body: Unrecognized keys in mapping: "{'retry': 1, 'batch': True, 'safe': False, 'bucket': 'vsp_firstbucket_v1'}")
```

after creating a first bucket. bucket name is vsp_firstbucket_v1

**Comment by Natim** [comment] 2017-04-03 17:08
ping @gabisurita is this a problem with the swagger validation?

**Comment by gabisurita** [comment] 2017-04-03 19:10
I can't see how this relates with the swagger validation. Do you have the server logs?

**Comment by gabisurita** [comment] 2017-04-04 00:39
I investigated this a bit and this is what I've got:

When I try using the admin with a local instance there's no log on the server, which means kinto-admin is probably trying to fetch something else and failing. I'm not familiar with the kinto-admin codebase, but it seems like kinto-admin is somehow trying to enforce SSL and crashing if it fails. 

When I tried using a heroku deployed master with HTTPS it worked well, when I changed the settings to HTTP it also crashed.

**Comment by Natim** [comment] 2017-04-04 07:13
Thanks you for investigating.

**Comment by n1k0** [comment] 2017-04-04 07:23
From the initial bug report description it seems like the client is sending the request options as part of the request body, which should never happen and is definitely a bug.

@vladp do you have sample code so we can inspect client calls?

**Comment by gabisurita** [comment] 2017-04-04 09:53
It came to me that maybe what I investigated and the initial report are two unrelated bugs. Haha

**Comment by vladp** [comment] 2017-04-04 23:52
@n1k0  the sources is exactly what I had pull from this GitHub repo on saturday, I did not modify a single line.

**Comment by glasserc** [comment] 2017-04-05 00:17
I was able to reproduce this locally with kinto-admin master and kinto master. I'll investigate.

**Comment by glasserc** [comment] 2017-04-05 20:52
Some investigation revealed that:

- The reason it's a POST is because the kinto-admin is doing a batch request to request the collections for all extant buckets.
- kinto-http `Bucket#listCollections` calls a method called `_bucketOptions` which copies any options from the client into the request, along with `bucket: "bucketname"` and `batch: false`.
- kinto master rejects these batch requests because they don't fit the colander schema of a batch request, which should only have `method`, `headers`, `path`, and `body` (and not e.g. `bucket`, `batch`, `safe`, `retry`).
- This doesn't appear to be limited to the `listCollections` method; when I modify just this method not to call `_bucketOptions`, I get a similar error a little later from other requests.

I'm pretty sure this is a bug in kinto-http.js, so I filed https://github.com/Kinto/kinto-http.js/pull/179 to start exploring it.

**Comment by n1k0** [comment] 2017-04-05 20:56
@glasserc nice debugging work here, kudos :+1:

**Comment by glasserc** [comment] 2017-04-10 20:40
Thanks for reporting this, @vladp. It's a pretty embarrassing issue but I think it should be resolved by Kinto/kinto-http.js#180. I've opened #422 to try to pull in that new version of the dependency, but I'm not experienced enough with the JS packaging ecosystem to know if this is the right fix. Anyhow, you should be able to pull from that branch and run against kinto master again. I'll keep this issue open until we release a kinto-admin that fixes the issue. Hope this helps, and let me know if you encounter any other issues.

**Comment by glasserc** [comment] 2017-04-11 18:40
Fixed in https://github.com/Kinto/kinto-admin/releases/tag/v1.13.1 and again in https://github.com/Kinto/kinto-admin/releases/tag/v1.13.2

**Closed by glasserc** 2017-04-11 18:40 UTC
