### ISSUE TITLE
Browser back/forward don't seem to work correctly, making it difficult to navigate

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto-admin#990] opened 2019-06-28 14:58 UTC
..to investigate :)

**Comment by alexcottner** [comment] 2024-04-25 20:11
I cannot seem to reproduce this anymore. Perhaps an update to our router package fixed it?

**Comment by alexcottner** [comment] 2024-10-14 21:45
Marking as closed, unable to reproduce at this point

**Closed by alexcottner** 2024-10-14 21:45 UTC
Labels: bug, ux
