### ISSUE TITLE
TypeError: Cannot read property 'username' of undefined

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto-admin#361] opened 2016-12-19 09:50 UTC
![screenshot from 2016-12-19 10-50-08](https://cloud.githubusercontent.com/assets/546692/21308155/f6e03b3e-c5d8-11e6-8ddb-d94d9d1e905f.png)

**Comment by leplatrem** [comment] 2016-12-19 10:11
Seems to happen when restoring session from local storage

**Comment by n1k0** [comment] 2016-12-27 14:53
What auth metod were you using when this happened?

**Comment by Natim** [comment] 2017-02-16 11:21
Closing as cannot reproduced.

**Closed by Natim** 2017-02-16 11:21 UTC
Labels: bug
