### ISSUE TITLE
Removing a record from the list comes back to a 404

### ISSUE THREAD

**Issue by Natim** [Kinto/kinto-admin#1077] opened 2019-10-03 09:49 UTC
- Sign in
- Go to the collection
- Create a record
- Remote it from the collection record list

![showcase](https://user-images.githubusercontent.com/229453/66117628-48948b00-e5d5-11e9-8188-927cb21c540f.gif)

**Comment by leplatrem** [comment] 2019-10-03 09:53
Do you mean deleting a record from a collection? Can you provide a step-by-step?

**Comment by leplatrem** [comment] 2020-01-23 15:41
I don't reproduce :/

**Comment by alexcottner** [comment] 2024-03-28 20:34
Closing this one out. Looks like we fixed this one already, can't reproduce with current UI.

**Closed by alexcottner** 2024-03-28 20:34 UTC
Labels: bug
